digitado = input('Digite algo: ')
print(type(digitado))
print('É alfabético?')
print(digitado.isalpha())
print('É numérico?')
print(digitado.isnumeric())
print('É alfa-numérico?')
print(digitado.isalnum())
print('Está em caixa alta?')
print(digitado.isupper())
print('Está em caixa baixa?')
print(digitado.islower())
print('É decimal?')
print(digitado.isdecimal())